# Generated by Django 2.2 on 2019-06-05 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzas', models.ManyToManyField(blank=True, to='menus.RegularPizza')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=40)),
                ('pizza_type', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(default='Draft', max_length=10)),
                ('pizza_toppings', models.ManyToManyField(blank=True, related_name='orders', to='menus.Topping')),
                ('sub_additions', models.ManyToManyField(blank=True, related_name='orders', to='menus.Additions')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=40)),
                ('pizza_type', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('username', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(default='Draft', max_length=10)),
                ('pizza_toppings', models.ManyToManyField(blank=True, related_name='confirmations', to='menus.Topping')),
                ('sub_additions', models.ManyToManyField(blank=True, related_name='confirmations', to='menus.Additions')),
            ],
        ),
    ]
