# Generated by Django 2.2 on 2019-06-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190603_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='regularPizza',
            new_name='regular',
        ),
    ]
